### PR TITLE
Add details regarding QA automation in CONTRIBUTING.md file.

### LINKED ISSUE #123: Document QA and development details
_This issue addresses a point of concern raised in the conversation of #122_

There seems to be a lot of implicit knowledge assumed regarding the GitHub actions we run.

After having documented the current release process, it might also be good to document how to run all of the QA tools in our current pipeline locally, during development.

Any other non-QA tooling should also be documented.

The following tools are used and should be documented:

- [x] jsonlint
- [x] yamllint
- [x] php-codesniffer
- [x] remark-lint

We use Pipeline-Components, which are basically just Docker images wrapped around a specific tool.

The options, from top to bottom are:

- Run GitHub actions locally with [act](https://github.com/nektos/act) `act --job job-name`
- Run a Pipeline-Component using docker `docker run -v $PWD:/code pipelinecomponents/some-tool --no-stdout .`
- Run a tool locally with NodeJS, Ruby, PHP, or whatever the tool is written in.

Not sure which route is the best to go and how much to explain or knowledge to assume (i.e. what to explain and where to link to the Remark docs).

Also: 
- Should information be added to the CONTRIBUTING file to document that code is expected to conform to specific rules?
- If installed in a local manner, are there files which should be added to the `.gitignore` file?

### PR DESCRIPTION
**Pull request by Potherca**
Fixes #123

### CODE REVIEW

**Comment by Potherca** [comment]
@jrfnl or @mjrider Does either of you have time to review my prose?

**Comment by jrfnl** [comment]
@Potherca Sorry that it's taken such a long time to get to this. I'd like to get this merged in before I pull the initial test setup PR.

Looking at it, it looks like some of the information is slightly out of date by now (Travis vs GH Actions and such). Have you got time to review and update it yourself ? Or would you like me to propose an update by adding a commit ?

**Comment by Potherca** [comment]
If you've got time, feel free to add. I'll move future branches from my fork to here so they can be more easily edited.

**Comment by jrfnl** [comment]
> If you've got time, feel free to add. I'll move future branches from my fork to here so they can be more easily edited.

I've created the update, but looks like the checkbox to allow maintainers to edit the PR has not been checked ?
A push to your fork on this PR branch is being rejected.

I'll send you a PR to update this PR 🙃

**Comment by jrfnl** [comment]
See: https://github.com/potherca-contrib/phpcodesniffer-composer-installer/pull/2

**Comment by Potherca** [comment]
@jrfnl I've merged your MR so you can merge my MR. 😬

**Pull request merged**
